(* Read a graph from a file,
 * Write a graph to a file. *)

open Graph

type path = string

(* Values are read as strings. *)
val from_file: path -> string graph

(* Similarly, we write only a string graph.
 * If necessary, use gmap (to be written by you) to prepare the input graph. *)
val write_file: path -> string graph -> unit

(* Takes a graph and exports it as a dot readable file *)
val export: path -> string graph -> unit

(* Reads a money sharing file which contains some names and the amount they payed *)
(* Returns a list of tuples of name and the amount payed *)
val read_money_sharing_file: path -> (string * int) list



(* The format of files is compatible with the files generated by:
   https://www-m9.ma.tum.de/graph-algorithms/flow-ford-fulkerson/index_en.html
*)
